project:
  type: website
  output-dir: docs

website:
  title: "AI Research Blog"
  # twitter-card: true
  google-analytics: "G-XPW0YXN0CK"
  open-graph: true
  favicon: deeprev.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Nyandwi
      - icon: twitter
        href: https://twitter.com/Jeande_d
      - icon: linkedin
        href: https://www.linkedin.com/in/nyandwi
format:
  html:
    theme: cosmo
    css: styles.css



