project:
  type: website
  output-dir: docs

website:
  title: "Deep Learning Revision"
  twitter-card: true
  open-graph: true
  favicon: deeprev.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



